# Generated by Django 4.0.1 on 2022-01-21 18:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleType', models.CharField(default='', max_length=100, null=True, unique=True)),
                ('order', models.CharField(default='', max_length=3, unique=True)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
            options={
                'verbose_name': 'Article Type',
                'verbose_name_plural': 'Article Types',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=200)),
                ('weblink', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Google_Scholar_Link', models.CharField(default='', max_length=300)),
                ('crossRef', models.CharField(default='', max_length=300)),
            ],
            options={
                'verbose_name': 'Citation',
                'verbose_name_plural': 'Citations',
            },
        ),
        migrations.CreateModel(
            name='ResearchInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researchInterest', models.CharField(default='', max_length=100, unique=True)),
                ('order', models.CharField(default='', max_length=3, unique=True)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
            options={
                'verbose_name': 'Research interest',
                'verbose_name_plural': 'Research interests',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_no', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Volume ',
                'verbose_name_plural': 'Volume s',
            },
        ),
        migrations.CreateModel(
            name='PublishedArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('abstract', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Publication List')),
                ('academicEditor', models.CharField(default='', max_length=200)),
                ('permissions', models.CharField(default='', max_length=200)),
                ('Received', models.DateTimeField(auto_now_add=True)),
                ('Revised', models.DateTimeField(blank=True)),
                ('Accepted', models.DateTimeField(blank=True)),
                ('Published', models.DateTimeField(blank=True)),
                ('publish_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('total_views', models.IntegerField(default=0)),
                ('article_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsweb.articletype', verbose_name='Article Type')),
                ('author', models.ManyToManyField(to='newsweb.Author', verbose_name='Authors')),
                ('citations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsweb.citation', verbose_name='Citations')),
                ('researchInterest', models.ManyToManyField(blank=True, null=True, to='newsweb.ResearchInterest')),
                ('volume_NO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsweb.volume', verbose_name='Volume NO')),
            ],
            options={
                'verbose_name': 'Published Article',
                'verbose_name_plural': 'Published Articles',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_no', models.IntegerField(default=1)),
                ('volume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsweb.articletype', verbose_name='Volume No')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
            },
        ),
    ]
