# Generated by Django 3.2.11 on 2022-01-29 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsweb', '0002_alter_publishedarticles_researchinterest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='authorName',
        ),
    ]
