# Generated by Django 3.2.11 on 2022-01-30 16:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsweb', '0003_rename_author_author_authorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedarticles',
            name='abstract',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Abstract'),
        ),
    ]
